name: CI - React Vite Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests (optional for now)
      - name: Run tests
        run: npm test --if-present

      # Step 5: Build project
      - name: Build project
        run: npm run build

      # Step 6: Upload build as artifact (optional)
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist
